version: "0.1"
environments:
  - name: development
    branch: development
    mode: pull-request
  - name: main
    branch: main
    mode: pull-request
apps:
  - name: test-repo
    path: ""
    text-resources:
      - path: src/lang/*.json
        format: simple-value-value
