version: "0.1"
environments:
  - name: main
    branch: main
    mode: pull-request
apps:
  - name: test-repo
    path: ""
    text-resources:
      - path: src/lang/fr-FR.json
        format: simple-value-value
