version: "0.1"
environments:
  - name: main
    branch: main
    mode: pull-request
apps:
  - name: test-repo
    path: src/
    text-resources:
      - path: lang/*.json
        format: flat-key-value
